-- Create Table: factories
CREATE TABLE IF NOT EXISTS factories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    location TEXT,
    owner_id UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Create Table: machines
CREATE TABLE IF NOT EXISTS machines (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    factory_id UUID REFERENCES factories(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type TEXT,
    status TEXT CHECK (status IN ('Active', 'Fault')),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Create Table: telemetry (Time-series data)
CREATE TABLE IF NOT EXISTS telemetry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id UUID REFERENCES machines(id) ON DELETE CASCADE,
    timestamp TIMESTAMPTZ DEFAULT now(),
    vibration DOUBLE PRECISION,
    temperature DOUBLE PRECISION,
    energy_kwh DOUBLE PRECISION
);

-- Create Table: ai_insights
CREATE TABLE IF NOT EXISTS ai_insights (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    machine_id UUID REFERENCES machines(id) ON DELETE CASCADE,
    alert_type TEXT,
    prediction_message TEXT,
    confidence_score DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Create Table: federated_updates
CREATE TABLE IF NOT EXISTS federated_updates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    factory_id UUID REFERENCES factories(id) ON DELETE CASCADE,
    model_version TEXT,
    encrypted_weights_blob TEXT,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Create Table: sustainability_logs (Green Ledger)
CREATE TABLE IF NOT EXISTS sustainability_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    factory_id UUID REFERENCES factories(id) ON DELETE CASCADE,
    date DATE DEFAULT CURRENT_DATE,
    energy_saved_kwh DOUBLE PRECISION,
    co2_offset_kg DOUBLE PRECISION,
    carbon_credits_earned DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Create Table: operator_leaderboard (Gamification)
CREATE TABLE IF NOT EXISTS operator_leaderboard (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    operator_name TEXT NOT NULL,
    factory_id UUID REFERENCES factories(id),
    uptime_score INTEGER DEFAULT 0,
    safety_compliance_score INTEGER DEFAULT 0,
    badges TEXT[], -- Array of badge names
    last_updated TIMESTAMPTZ DEFAULT now()
);

-- 🤖 PREDICTIVE MAINTENANCE TRIGGER 🤖
-- Logic: If vibration > 4.5, automatically trigger an AI Insight alert.

CREATE OR REPLACE FUNCTION trigger_predictive_insight()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.vibration > 4.5 THEN
        INSERT INTO ai_insights (machine_id, alert_type, prediction_message, confidence_score)
        VALUES (
            NEW.machine_id, 
            'Critical Vibration', 
            'Pattern analysis suggests imminent bearing failure. Schedule inspection immediately.', 
            0.92
        );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS on_vibration_spike ON telemetry;
CREATE TRIGGER on_vibration_spike
AFTER INSERT ON telemetry
FOR EACH ROW
EXECUTE FUNCTION trigger_predictive_insight();

-- Enable RLS for new tables
ALTER TABLE sustainability_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE operator_leaderboard ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Access" ON sustainability_logs FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON operator_leaderboard FOR SELECT USING (true);

-- Enable Row Level Security (RLS)
ALTER TABLE factories ENABLE ROW LEVEL SECURITY;
ALTER TABLE machines ENABLE ROW LEVEL SECURITY;
ALTER TABLE telemetry ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE federated_updates ENABLE ROW LEVEL SECURITY;

-- Simple Policies (Allow public read for dashboard, authenticated write)
-- Note: Replace with more specific policies as needed.
CREATE POLICY "Public Read Access" ON factories FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON machines FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON telemetry FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON ai_insights FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON federated_updates FOR SELECT USING (true);
